// <auto-generated />
using System;
using KestenApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KestenApp.Data.Migrations
{
    [DbContext(typeof(KestenDbContext))]
    [Migration("20230729095339_addVarietyHifas")]
    partial class addVarietyHifas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KestenApp.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KestenApp.Data.Models.FruitSize", b =>
                {
                    b.Property<int>("FruitSizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FruitSizeId"), 1L, 1);

                    b.Property<int?>("FruitsPerKgMax")
                        .HasColumnType("int");

                    b.Property<int?>("FruitsPerKgMin")
                        .HasColumnType("int");

                    b.Property<int?>("FruitsWeightMax")
                        .HasColumnType("int");

                    b.Property<int?>("FruitsWeightMin")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FruitSizeId");

                    b.ToTable("FruitSizes");

                    b.HasData(
                        new
                        {
                            FruitSizeId = 1,
                            Name = "Varying"
                        },
                        new
                        {
                            FruitSizeId = 2,
                            FruitsPerKgMax = 1000,
                            FruitsPerKgMin = 84,
                            FruitsWeightMax = 12,
                            FruitsWeightMin = 1,
                            Name = "Small"
                        },
                        new
                        {
                            FruitSizeId = 3,
                            FruitsPerKgMax = 83,
                            FruitsPerKgMin = 67,
                            FruitsWeightMax = 15,
                            FruitsWeightMin = 13,
                            Name = "Medium"
                        },
                        new
                        {
                            FruitSizeId = 4,
                            FruitsPerKgMax = 66,
                            FruitsPerKgMin = 56,
                            FruitsWeightMax = 18,
                            FruitsWeightMin = 16,
                            Name = "Large"
                        },
                        new
                        {
                            FruitSizeId = 5,
                            FruitsPerKgMax = 55,
                            FruitsPerKgMin = 15,
                            FruitsWeightMax = 100,
                            FruitsWeightMin = 18,
                            Name = "XL"
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.Garden", b =>
                {
                    b.Property<Guid>("GardenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GardenId");

                    b.HasIndex("UserId");

                    b.ToTable("Gardens", (string)null);

                    b.HasData(
                        new
                        {
                            GardenId = new Guid("6cc4edb7-1110-43ab-8c16-5f245ebd118c"),
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsPublished = true,
                            Name = "Sharp Mound",
                            UserId = new Guid("09e77621-fac4-4150-b64c-3e5c2b1a40ee")
                        },
                        new
                        {
                            GardenId = new Guid("de1609f0-bd9c-472d-b453-8e167c690b8f"),
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsPublished = true,
                            Name = "Veslets G",
                            UserId = new Guid("09e77621-fac4-4150-b64c-3e5c2b1a40ee")
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.Species", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpeciesId"), 1L, 1);

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortLatinName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpeciesId");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            SpeciesId = 1,
                            CommonName = "European chestnut",
                            LatinName = "Castanea sativa",
                            ShortLatinName = "Sativa"
                        },
                        new
                        {
                            SpeciesId = 2,
                            CommonName = "Japanese chestnut",
                            LatinName = "Castanea crenata",
                            ShortLatinName = "Crenata"
                        },
                        new
                        {
                            SpeciesId = 3,
                            CommonName = "Chinese chestnut",
                            LatinName = "Castanea mollissima",
                            ShortLatinName = "Mollissima"
                        },
                        new
                        {
                            SpeciesId = 4,
                            CommonName = "American chestnut",
                            LatinName = "Castanea dentata",
                            ShortLatinName = "Dentata"
                        },
                        new
                        {
                            SpeciesId = 5,
                            CommonName = "Allegheny chinkapin",
                            LatinName = "Castanea pumila",
                            ShortLatinName = "Pumila"
                        },
                        new
                        {
                            SpeciesId = 6,
                            CommonName = "Ozark chinkapin",
                            LatinName = "Castanea ozarkensis",
                            ShortLatinName = "Ozarkensis"
                        },
                        new
                        {
                            SpeciesId = 7,
                            CommonName = "Chinese chinkapin",
                            LatinName = "Castanea henryi",
                            ShortLatinName = "Henryi"
                        },
                        new
                        {
                            SpeciesId = 8,
                            CommonName = "Seguin's chestnut",
                            LatinName = "Castanea seguinii",
                            ShortLatinName = "Seguinii"
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.Specimen", b =>
                {
                    b.Property<Guid>("SpecimenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("Elevation")
                        .HasPrecision(9, 6)
                        .HasColumnType("int");

                    b.Property<Guid?>("GardenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("GraftedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("PlantedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SowedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SpecimenId");

                    b.HasIndex("GardenId");

                    b.HasIndex("UserId");

                    b.HasIndex("VarietyId");

                    b.ToTable("Specimens", (string)null);

                    b.HasData(
                        new
                        {
                            SpecimenId = new Guid("1db462cd-ebf6-45ab-9782-a8255e04b66a"),
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elevation = 642,
                            GardenId = new Guid("6cc4edb7-1110-43ab-8c16-5f245ebd118c"),
                            IsActive = true,
                            Latitude = "43°1'2.27\"N",
                            Longitude = "23°37'28.57\"E",
                            Name = "Marigoule 2019",
                            PlantedOnDate = new DateTime(2019, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("09e77621-fac4-4150-b64c-3e5c2b1a40ee"),
                            VarietyId = new Guid("fba92871-4a3c-4978-fcd6-08db87b43c2d")
                        },
                        new
                        {
                            SpecimenId = new Guid("abd2f71e-ccfa-4fea-850c-ff58c18a58ef"),
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elevation = 641,
                            GardenId = new Guid("6cc4edb7-1110-43ab-8c16-5f245ebd118c"),
                            IsActive = true,
                            Name = "Marsol 2022",
                            PlantedOnDate = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("09e77621-fac4-4150-b64c-3e5c2b1a40ee"),
                            VarietyId = new Guid("8fc8f311-3ce9-42e2-fcd7-08db87b43c2d")
                        },
                        new
                        {
                            SpecimenId = new Guid("2a966622-0ad5-4129-99ba-419d59b4d2d5"),
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elevation = 645,
                            GardenId = new Guid("6cc4edb7-1110-43ab-8c16-5f245ebd118c"),
                            IsActive = true,
                            Name = "Hifas 2019",
                            PlantedOnDate = new DateTime(2019, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("09e77621-fac4-4150-b64c-3e5c2b1a40ee"),
                            VarietyId = new Guid("34cb004b-20d2-4444-beb3-5e7e80e1f3a3")
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.Variety", b =>
                {
                    b.Property<Guid>("VarietyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BuddingPeriod")
                        .HasColumnType("int");

                    b.Property<int>("ChestnutBlightResistance")
                        .HasColumnType("int");

                    b.Property<int>("Conservation")
                        .HasColumnType("int");

                    b.Property<int>("Crop")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FloweringPeriod")
                        .HasColumnType("int");

                    b.Property<int>("InkDiseaseResistance")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsMarron")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("MaturityPeriod")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Peeling")
                        .HasColumnType("int");

                    b.Property<int>("PollenType")
                        .HasColumnType("int");

                    b.Property<int>("Vigor")
                        .HasColumnType("int");

                    b.HasKey("VarietyId");

                    b.ToTable("Varieties", (string)null);

                    b.HasData(
                        new
                        {
                            VarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 3,
                            Conservation = 2,
                            Crop = 3,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bouche de Bétizac is a French chestnut cultivar developed in 1962 by INRA at the station of Malemort-sur-Corrèze near Brive. It is a controlled hybrid between Castanea sativa and Castanea crenata (female Bouche rouge × male Castanea crenata CA04). This variety produces large to very large chestnuts. It has very good flavor for a hybrid. With Marigoule, it is the variety currently most cultivated in the French chestnut groves because it is very productive (3 tons per hectare on average). Its fruit is bright, light chestnut-brown quickly turning brown and dark brown.",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 1,
                            IsActive = true,
                            IsMarron = true,
                            IsPublished = true,
                            MaturityPeriod = 2,
                            Name = "Bouche de Bétizac",
                            Peeling = 3,
                            PollenType = 1,
                            Vigor = 2
                        },
                        new
                        {
                            VarietyId = new Guid("fba92871-4a3c-4978-fcd6-08db87b43c2d"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 2,
                            Conservation = 3,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Marigoule is the name of a french hybrid of chestnut (synonym M.15 or CA 15), cross between a European chestnut (Castanea sativa) and Japanese (Castanea crenata). In 1986, it originated from a Migoule orchard in Ussac in Corrèze. Marigoule (a contraction of Marron of Migoule) is a very tasty chestnut. It should be planted in rather low altitude in very sunny areas and protected from the wind (up to 300 m elevation for South-West orchard orientation or up to 400 m elevation in South-East orchard orientation). Otherwise its productivity remains small. In France, it is grown mainly South of the Dordogne and Lot-et-Garonne for the fresh market production because of the nuts beautiful appearance.",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 3,
                            IsActive = true,
                            IsMarron = true,
                            IsPublished = true,
                            MaturityPeriod = 3,
                            Name = "Marigoule",
                            Peeling = 3,
                            PollenType = 2,
                            Vigor = 3
                        },
                        new
                        {
                            VarietyId = new Guid("8fc8f311-3ce9-42e2-fcd7-08db87b43c2d"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 3,
                            Conservation = 3,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 2, 0, DateTimeKind.Unspecified),
                            Description = "Marsol (aka Marisol) is a natural chestnut hybrid, a cross between a European chestnut (Castanea sativa) and Japanese (Castanea crenata) (CA 07). INRA produced this variety from Lalevade-d'Ardèche. It is mainly used as a rootstock because of its good graft compatibility with many varieties. As a rootstock, it is more vigorous than Maraval (equal to Bouche de Betizac or Comballe).",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 3,
                            IsActive = true,
                            IsMarron = true,
                            IsPublished = true,
                            MaturityPeriod = 3,
                            Name = "Marsol",
                            Peeling = 3,
                            PollenType = 3,
                            Vigor = 4
                        },
                        new
                        {
                            VarietyId = new Guid("becf003c-6915-4018-8628-c2cb3fd8839c"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 1,
                            Conservation = 2,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 3, 0, DateTimeKind.Unspecified),
                            Description = "The Precoce Migoule is a chestnut hybrid (CA 48), a natural cross between a European chestnut (Castanea sativa) and a Japanese chestnut (Castanea crenata). It was discovered by J. Dufrenoy at the orchard of Migoule in Brive-la-Gaillarde. The tree is vigorous and erect growing with growth of a metre (3 ft) or more in a season if the conditions are right. It is a large sized chestnut tree with height reaching 20 m (60 ft) or more and 7.5-10 m (25-35 ft) wide. Trees start to bear after 3 to 5 years. Full nut production in 12 - 20 years depending on the location.",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 2,
                            IsActive = true,
                            IsMarron = true,
                            IsPublished = true,
                            MaturityPeriod = 2,
                            Name = "Précoce Migoule",
                            Peeling = 3,
                            PollenType = 2,
                            Vigor = 2
                        },
                        new
                        {
                            VarietyId = new Guid("34cb004b-20d2-4444-beb3-5e7e80e1f3a3"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 2,
                            Conservation = 2,
                            Crop = 2,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 4, 0, DateTimeKind.Unspecified),
                            Description = "Resistant hybrid chestnut from Hifas Foresta.",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 3,
                            IsActive = true,
                            IsMarron = true,
                            IsPublished = true,
                            MaturityPeriod = 2,
                            Name = "Hifas",
                            Peeling = 2,
                            PollenType = 3,
                            Vigor = 4
                        },
                        new
                        {
                            VarietyId = new Guid("a83dbdc7-8fb7-4673-9755-ff7f4aa093e7"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 5, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Pandora",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("210b4973-40a3-4f4e-84b7-46447384a4d4"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 6, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Nevada",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("5d1e8a78-b6d3-4976-9238-be63602177ec"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 7, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Long Street",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("e54df2eb-b85b-4da0-a09e-acea8bd95cf4"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 8, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "AU 2-18",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("96fdbe3e-7875-4cc4-9597-60379cb1df8f"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 9, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "AU Super",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("8c46db33-3bd3-4106-bb8e-47af2dde78b1"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 10, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Black Satin",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("1c0fada6-af70-438f-9cbe-f28702e09fff"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 11, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Chushuhong",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("e27967cf-e742-4d08-be60-ba0c3df220cc"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 12, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Emalyn's Purple",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("ef9de558-6cbe-4261-b760-af564ef7fb67"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 13, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Gideon",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("a6e6b663-ae47-474a-91f3-0c9f91f92353"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 14, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Jenny",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("17c44322-e9ea-4320-b7f5-2985f63a850d"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 15, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Jiaoza",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("044f9dfc-3480-4847-8c87-f7f615b1dd33"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 16, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Payne",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("680e76a6-d17e-48f0-8d88-0105db2932dd"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 17, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Peach",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("5fb1e619-ef00-49e5-9cad-6dfdd1b10eb3"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 18, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Qing",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("a9347582-5bd8-4d7e-b4ee-c5da5e6c0758"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 19, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Qingza",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("f9446ab0-d5d7-43e4-a963-1d65025c09a7"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 20, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Royalmark",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("5bcda061-c025-4c08-bfb0-63490e7dbcde"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 21, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "YGF",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("0ecf9143-c0c6-4446-be03-bb70effe1c1e"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Yixian Large",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyFruitSize", b =>
                {
                    b.Property<Guid>("VarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FruitSizeId")
                        .HasColumnType("int");

                    b.HasKey("VarietyId", "FruitSizeId");

                    b.HasIndex("FruitSizeId");

                    b.ToTable("VarietyFruitSizes", (string)null);

                    b.HasData(
                        new
                        {
                            VarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77"),
                            FruitSizeId = 5
                        },
                        new
                        {
                            VarietyId = new Guid("fba92871-4a3c-4978-fcd6-08db87b43c2d"),
                            FruitSizeId = 4
                        },
                        new
                        {
                            VarietyId = new Guid("fba92871-4a3c-4978-fcd6-08db87b43c2d"),
                            FruitSizeId = 5
                        },
                        new
                        {
                            VarietyId = new Guid("8fc8f311-3ce9-42e2-fcd7-08db87b43c2d"),
                            FruitSizeId = 5
                        },
                        new
                        {
                            VarietyId = new Guid("becf003c-6915-4018-8628-c2cb3fd8839c"),
                            FruitSizeId = 3
                        },
                        new
                        {
                            VarietyId = new Guid("becf003c-6915-4018-8628-c2cb3fd8839c"),
                            FruitSizeId = 4
                        },
                        new
                        {
                            VarietyId = new Guid("34cb004b-20d2-4444-beb3-5e7e80e1f3a3"),
                            FruitSizeId = 4
                        },
                        new
                        {
                            VarietyId = new Guid("34cb004b-20d2-4444-beb3-5e7e80e1f3a3"),
                            FruitSizeId = 5
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyGraftingCompatibility", b =>
                {
                    b.Property<Guid>("RootstockVarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GraftedVarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RootstockVarietyId", "GraftedVarietyId");

                    b.HasIndex("GraftedVarietyId");

                    b.ToTable("VarietyGrafting", (string)null);

                    b.HasData(
                        new
                        {
                            RootstockVarietyId = new Guid("8fc8f311-3ce9-42e2-fcd7-08db87b43c2d"),
                            GraftedVarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77")
                        },
                        new
                        {
                            RootstockVarietyId = new Guid("8fc8f311-3ce9-42e2-fcd7-08db87b43c2d"),
                            GraftedVarietyId = new Guid("becf003c-6915-4018-8628-c2cb3fd8839c")
                        },
                        new
                        {
                            RootstockVarietyId = new Guid("fba92871-4a3c-4978-fcd6-08db87b43c2d"),
                            GraftedVarietyId = new Guid("becf003c-6915-4018-8628-c2cb3fd8839c")
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyImage", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImageId");

                    b.HasIndex("VarietyId");

                    b.ToTable("VarietyImages", (string)null);

                    b.HasData(
                        new
                        {
                            ImageId = new Guid("be9cca3d-4e9a-4e75-b813-9279f79f7f75"),
                            VarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77")
                        },
                        new
                        {
                            ImageId = new Guid("bf77ff2d-a488-4f6d-847b-3c880239a53f"),
                            VarietyId = new Guid("fba92871-4a3c-4978-fcd6-08db87b43c2d")
                        },
                        new
                        {
                            ImageId = new Guid("ee93870c-a4ad-46f7-b5dc-f36ae12ed3a3"),
                            VarietyId = new Guid("8fc8f311-3ce9-42e2-fcd7-08db87b43c2d")
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyPollenCompatibility", b =>
                {
                    b.Property<Guid>("PollenizerVarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetVarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PollenizerVarietyId", "TargetVarietyId");

                    b.HasIndex("TargetVarietyId");

                    b.ToTable("VarietyPollenizers", (string)null);

                    b.HasData(
                        new
                        {
                            PollenizerVarietyId = new Guid("fba92871-4a3c-4978-fcd6-08db87b43c2d"),
                            TargetVarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77")
                        },
                        new
                        {
                            PollenizerVarietyId = new Guid("8fc8f311-3ce9-42e2-fcd7-08db87b43c2d"),
                            TargetVarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77")
                        },
                        new
                        {
                            PollenizerVarietyId = new Guid("becf003c-6915-4018-8628-c2cb3fd8839c"),
                            TargetVarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77")
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietySpecies", b =>
                {
                    b.Property<Guid>("VarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("VarietyId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("VarietySpecies");

                    b.HasData(
                        new
                        {
                            VarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77"),
                            SpeciesId = 1
                        },
                        new
                        {
                            VarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77"),
                            SpeciesId = 2
                        },
                        new
                        {
                            VarietyId = new Guid("fba92871-4a3c-4978-fcd6-08db87b43c2d"),
                            SpeciesId = 1
                        },
                        new
                        {
                            VarietyId = new Guid("fba92871-4a3c-4978-fcd6-08db87b43c2d"),
                            SpeciesId = 2
                        },
                        new
                        {
                            VarietyId = new Guid("8fc8f311-3ce9-42e2-fcd7-08db87b43c2d"),
                            SpeciesId = 1
                        },
                        new
                        {
                            VarietyId = new Guid("8fc8f311-3ce9-42e2-fcd7-08db87b43c2d"),
                            SpeciesId = 2
                        },
                        new
                        {
                            VarietyId = new Guid("becf003c-6915-4018-8628-c2cb3fd8839c"),
                            SpeciesId = 1
                        },
                        new
                        {
                            VarietyId = new Guid("becf003c-6915-4018-8628-c2cb3fd8839c"),
                            SpeciesId = 2
                        },
                        new
                        {
                            VarietyId = new Guid("a83dbdc7-8fb7-4673-9755-ff7f4aa093e7"),
                            SpeciesId = 3
                        },
                        new
                        {
                            VarietyId = new Guid("a83dbdc7-8fb7-4673-9755-ff7f4aa093e7"),
                            SpeciesId = 8
                        },
                        new
                        {
                            VarietyId = new Guid("34cb004b-20d2-4444-beb3-5e7e80e1f3a3"),
                            SpeciesId = 1
                        },
                        new
                        {
                            VarietyId = new Guid("34cb004b-20d2-4444-beb3-5e7e80e1f3a3"),
                            SpeciesId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "ddda0b74-66c4-49c1-95c9-538fba054854",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "3892ea99-ce0d-4d33-abf9-bbd024a1a0b1",
                            Name = "Expert",
                            NormalizedName = "EXPERT"
                        },
                        new
                        {
                            Id = "4e99c46a-03ce-4e17-9585-49d47059d9e3",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KestenApp.Data.Models.Garden", b =>
                {
                    b.HasOne("KestenApp.Data.Models.ApplicationUser", "User")
                        .WithMany("Gardens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KestenApp.Data.Models.Specimen", b =>
                {
                    b.HasOne("KestenApp.Data.Models.Garden", "Garden")
                        .WithMany("Specimens")
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KestenApp.Data.Models.ApplicationUser", "User")
                        .WithMany("Specimens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.Variety", "Variety")
                        .WithMany("Specimens")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Garden");

                    b.Navigation("User");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyFruitSize", b =>
                {
                    b.HasOne("KestenApp.Data.Models.FruitSize", "FruitSize")
                        .WithMany("Varieties")
                        .HasForeignKey("FruitSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.Variety", "Variety")
                        .WithMany("FruitSizes")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FruitSize");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyGraftingCompatibility", b =>
                {
                    b.HasOne("KestenApp.Data.Models.Variety", "GraftedVariety")
                        .WithMany("IsGraftedOn")
                        .HasForeignKey("GraftedVarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.Variety", "RootstockVariety")
                        .WithMany("IsRootstockFor")
                        .HasForeignKey("RootstockVarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GraftedVariety");

                    b.Navigation("RootstockVariety");
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyImage", b =>
                {
                    b.HasOne("KestenApp.Data.Models.Variety", "Variety")
                        .WithMany("VarietyImages")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyPollenCompatibility", b =>
                {
                    b.HasOne("KestenApp.Data.Models.Variety", "PollenizerVariety")
                        .WithMany("IsPollenizerFor")
                        .HasForeignKey("PollenizerVarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.Variety", "TargetVariety")
                        .WithMany("IsPollenizedBy")
                        .HasForeignKey("TargetVarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PollenizerVariety");

                    b.Navigation("TargetVariety");
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietySpecies", b =>
                {
                    b.HasOne("KestenApp.Data.Models.Species", "Species")
                        .WithMany("Varieties")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.Variety", "Variety")
                        .WithMany("Species")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("KestenApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("KestenApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("KestenApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KestenApp.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Gardens");

                    b.Navigation("Specimens");
                });

            modelBuilder.Entity("KestenApp.Data.Models.FruitSize", b =>
                {
                    b.Navigation("Varieties");
                });

            modelBuilder.Entity("KestenApp.Data.Models.Garden", b =>
                {
                    b.Navigation("Specimens");
                });

            modelBuilder.Entity("KestenApp.Data.Models.Species", b =>
                {
                    b.Navigation("Varieties");
                });

            modelBuilder.Entity("KestenApp.Data.Models.Variety", b =>
                {
                    b.Navigation("FruitSizes");

                    b.Navigation("IsGraftedOn");

                    b.Navigation("IsPollenizedBy");

                    b.Navigation("IsPollenizerFor");

                    b.Navigation("IsRootstockFor");

                    b.Navigation("Species");

                    b.Navigation("Specimens");

                    b.Navigation("VarietyImages");
                });
#pragma warning restore 612, 618
        }
    }
}
