// <auto-generated />
using System;
using KestenApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KestenApp.Data.Migrations
{
    [DbContext(typeof(KestenDbContext))]
    [Migration("20230728074448_specimensAndGardens")]
    partial class specimensAndGardens
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KestenApp.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KestenApp.Data.Models.FruitSize", b =>
                {
                    b.Property<int>("FruitSizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FruitSizeId"), 1L, 1);

                    b.Property<int?>("FruitsPerKgMax")
                        .HasColumnType("int");

                    b.Property<int?>("FruitsPerKgMin")
                        .HasColumnType("int");

                    b.Property<int?>("FruitsWeightMax")
                        .HasColumnType("int");

                    b.Property<int?>("FruitsWeightMin")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FruitSizeId");

                    b.ToTable("FruitSizes");

                    b.HasData(
                        new
                        {
                            FruitSizeId = 1,
                            Name = "Varying"
                        },
                        new
                        {
                            FruitSizeId = 2,
                            FruitsPerKgMax = 1000,
                            FruitsPerKgMin = 84,
                            FruitsWeightMax = 12,
                            FruitsWeightMin = 1,
                            Name = "Small"
                        },
                        new
                        {
                            FruitSizeId = 3,
                            FruitsPerKgMax = 83,
                            FruitsPerKgMin = 67,
                            FruitsWeightMax = 15,
                            FruitsWeightMin = 13,
                            Name = "Medium"
                        },
                        new
                        {
                            FruitSizeId = 4,
                            FruitsPerKgMax = 66,
                            FruitsPerKgMin = 56,
                            FruitsWeightMax = 18,
                            FruitsWeightMin = 16,
                            Name = "Large"
                        },
                        new
                        {
                            FruitSizeId = 5,
                            FruitsPerKgMax = 55,
                            FruitsPerKgMin = 15,
                            FruitsWeightMax = 100,
                            FruitsWeightMin = 18,
                            Name = "XL"
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.Garden", b =>
                {
                    b.Property<Guid>("GardenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GardenId");

                    b.HasIndex("UserId");

                    b.ToTable("Gardens", (string)null);

                    b.HasData(
                        new
                        {
                            GardenId = new Guid("6cc4edb7-1110-43ab-8c16-5f245ebd118c"),
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sharp Mound",
                            UserId = new Guid("09e77621-fac4-4150-b64c-3e5c2b1a40ee")
                        },
                        new
                        {
                            GardenId = new Guid("b4641ca0-689f-4f8a-9654-984940045276"),
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Veslets G",
                            UserId = new Guid("09e77621-fac4-4150-b64c-3e5c2b1a40ee")
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.Species", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpeciesId"), 1L, 1);

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortLatinName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpeciesId");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            SpeciesId = 1,
                            CommonName = "European chestnut",
                            LatinName = "Castanea sativa",
                            ShortLatinName = "Sativa"
                        },
                        new
                        {
                            SpeciesId = 2,
                            CommonName = "Japanese chestnut",
                            LatinName = "Castanea crenata",
                            ShortLatinName = "Crenata"
                        },
                        new
                        {
                            SpeciesId = 3,
                            CommonName = "Chinese chestnut",
                            LatinName = "Castanea mollissima",
                            ShortLatinName = "Mollissima"
                        },
                        new
                        {
                            SpeciesId = 4,
                            CommonName = "American chestnut",
                            LatinName = "Castanea dentata",
                            ShortLatinName = "Dentata"
                        },
                        new
                        {
                            SpeciesId = 5,
                            CommonName = "Allegheny chinkapin",
                            LatinName = "Castanea pumila",
                            ShortLatinName = "Pumila"
                        },
                        new
                        {
                            SpeciesId = 6,
                            CommonName = "Ozark chinkapin",
                            LatinName = "Castanea ozarkensis",
                            ShortLatinName = "Ozarkensis"
                        },
                        new
                        {
                            SpeciesId = 7,
                            CommonName = "Chinese chinkapin",
                            LatinName = "Castanea henryi",
                            ShortLatinName = "Henryi"
                        },
                        new
                        {
                            SpeciesId = 8,
                            CommonName = "Seguin's chestnut",
                            LatinName = "Castanea seguinii",
                            ShortLatinName = "Seguinii"
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.Specimen", b =>
                {
                    b.Property<Guid>("SpecimenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("Elevation")
                        .HasPrecision(9, 6)
                        .HasColumnType("int");

                    b.Property<Guid?>("GardenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("GraftedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("PlantedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SowedOnDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SpecimenId");

                    b.HasIndex("GardenId");

                    b.HasIndex("UserId");

                    b.HasIndex("VarietyId");

                    b.ToTable("Specimens", (string)null);

                    b.HasData(
                        new
                        {
                            SpecimenId = new Guid("940f5580-22d0-4bc3-b36e-bc14f0475b94"),
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elevation = 642,
                            GardenId = new Guid("6cc4edb7-1110-43ab-8c16-5f245ebd118c"),
                            Latitude = "43°1'2.27\"N",
                            Longitude = "23°37'28.57\"E",
                            Name = "Marigoule 2019",
                            PlantedOnDate = new DateTime(2019, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("09e77621-fac4-4150-b64c-3e5c2b1a40ee"),
                            VarietyId = new Guid("fba92871-4a3c-4978-fcd6-08db87b43c2d")
                        },
                        new
                        {
                            SpecimenId = new Guid("f7766229-07fb-4d89-8ef4-95902eae41cd"),
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elevation = 641,
                            GardenId = new Guid("6cc4edb7-1110-43ab-8c16-5f245ebd118c"),
                            Name = "Marsol 2022",
                            PlantedOnDate = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("09e77621-fac4-4150-b64c-3e5c2b1a40ee"),
                            VarietyId = new Guid("8fc8f311-3ce9-42e2-fcd7-08db87b43c2d")
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.Variety", b =>
                {
                    b.Property<Guid>("VarietyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BuddingPeriod")
                        .HasColumnType("int");

                    b.Property<int>("ChestnutBlightResistance")
                        .HasColumnType("int");

                    b.Property<int>("Conservation")
                        .HasColumnType("int");

                    b.Property<int>("Crop")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FloweringPeriod")
                        .HasColumnType("int");

                    b.Property<int>("InkDiseaseResistance")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsMarron")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("MaturityPeriod")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Peeling")
                        .HasColumnType("int");

                    b.Property<int>("PollenType")
                        .HasColumnType("int");

                    b.Property<int>("Vigor")
                        .HasColumnType("int");

                    b.HasKey("VarietyId");

                    b.ToTable("Varieties", (string)null);

                    b.HasData(
                        new
                        {
                            VarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 3,
                            Conservation = 2,
                            Crop = 3,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bouche de Bétizac is a French chestnut cultivar developed in 1962 by INRA at the station of Malemort-sur-Corrèze near Brive. It is a controlled hybrid between Castanea sativa and Castanea crenata (female Bouche rouge × male Castanea crenata CA04). This variety produces large to very large chestnuts. It has very good flavor for a hybrid. With Marigoule, it is the variety currently most cultivated in the French chestnut groves because it is very productive (3 tons per hectare on average). Its fruit is bright, light chestnut-brown quickly turning brown and dark brown.",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 1,
                            IsActive = true,
                            IsMarron = true,
                            IsPublished = true,
                            MaturityPeriod = 2,
                            Name = "Bouche de Bétizac",
                            Peeling = 3,
                            PollenType = 1,
                            Vigor = 2
                        },
                        new
                        {
                            VarietyId = new Guid("fba92871-4a3c-4978-fcd6-08db87b43c2d"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 2,
                            Conservation = 3,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Marigoule is the name of a french hybrid of chestnut (synonym M.15 or CA 15), cross between a European chestnut (Castanea sativa) and Japanese (Castanea crenata). In 1986, it originated from a Migoule orchard in Ussac in Corrèze. Marigoule (a contraction of Marron of Migoule) is a very tasty chestnut. It should be planted in rather low altitude in very sunny areas and protected from the wind (up to 300 m elevation for South-West orchard orientation or up to 400 m elevation in South-East orchard orientation). Otherwise its productivity remains small. In France, it is grown mainly South of the Dordogne and Lot-et-Garonne for the fresh market production because of the nuts beautiful appearance.",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 3,
                            IsActive = true,
                            IsMarron = true,
                            IsPublished = true,
                            MaturityPeriod = 3,
                            Name = "Marigoule",
                            Peeling = 3,
                            PollenType = 2,
                            Vigor = 3
                        },
                        new
                        {
                            VarietyId = new Guid("8fc8f311-3ce9-42e2-fcd7-08db87b43c2d"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 3,
                            Conservation = 3,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 2, 0, DateTimeKind.Unspecified),
                            Description = "Marsol (aka Marisol) is a natural chestnut hybrid, a cross between a European chestnut (Castanea sativa) and Japanese (Castanea crenata) (CA 07). INRA produced this variety from Lalevade-d'Ardèche. It is mainly used as a rootstock because of its good graft compatibility with many varieties. As a rootstock, it is more vigorous than Maraval (equal to Bouche de Betizac or Comballe).",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 3,
                            IsActive = true,
                            IsMarron = true,
                            IsPublished = true,
                            MaturityPeriod = 3,
                            Name = "Marsol",
                            Peeling = 3,
                            PollenType = 3,
                            Vigor = 4
                        },
                        new
                        {
                            VarietyId = new Guid("ce7bf581-cd82-497e-a813-319dd7fcd922"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 1,
                            Conservation = 2,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 3, 0, DateTimeKind.Unspecified),
                            Description = "The Precoce Migoule is a chestnut hybrid (CA 48), a natural cross between a European chestnut (Castanea sativa) and a Japanese chestnut (Castanea crenata). It was discovered by J. Dufrenoy at the orchard of Migoule in Brive-la-Gaillarde. The tree is vigorous and erect growing with growth of a metre (3 ft) or more in a season if the conditions are right. It is a large sized chestnut tree with height reaching 20 m (60 ft) or more and 7.5-10 m (25-35 ft) wide. Trees start to bear after 3 to 5 years. Full nut production in 12 - 20 years depending on the location.",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 2,
                            IsActive = true,
                            IsMarron = true,
                            IsPublished = true,
                            MaturityPeriod = 2,
                            Name = "Précoce Migoule",
                            Peeling = 3,
                            PollenType = 2,
                            Vigor = 2
                        },
                        new
                        {
                            VarietyId = new Guid("dd423ce9-41e7-4c86-804a-9f4ade0b08f1"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 4, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Pandora",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("48f0e37f-4cd1-4abc-a30a-b3e4ce78b012"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 5, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Nevada",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("897b29c1-1a95-49cc-8534-185221078582"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 6, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Long Street",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("8490211f-b230-4765-9fd2-237703ad0261"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 7, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "AU 2-18",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("b81e5d7f-c595-49ac-8a37-b0ba3ccfe071"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 8, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "AU Super",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("88dfa51e-7940-46c1-9182-1b3f50a3fafe"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 9, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Black Satin",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("cd960168-1b25-418e-bcd5-e6e561cc00c4"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 10, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Chushuhong",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("379d80d8-cf0d-4c04-8358-c3e7be2f1fda"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 11, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Emalyn's Purple",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("609fdff3-5e9c-4693-9e9e-fdb9d0361849"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 12, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Gideon",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("4662db63-0f99-44b3-8e05-fbe173e9a701"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 13, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Jenny",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("6c37f6b8-c2e3-412f-9291-2e3274df8470"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 14, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Jiaoza",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("cebbcf50-30b8-49f0-9646-ac1b3014dfc5"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 15, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Payne",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("1a5fd211-d636-4c24-a2af-07c604f288c7"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 16, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Peach",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("e0f6acb9-20d2-4851-ac21-377f92abdee3"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 17, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Qing",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("f0625673-6553-4c96-a0cd-e253f3a2f0c0"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 18, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Qingza",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("ac732ef4-0373-49d8-82ac-9af1969604d9"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 19, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Royalmark",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("65db8de8-c4b1-4d12-be07-386468b4c4cc"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(2023, 7, 7, 7, 0, 20, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "YGF",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        },
                        new
                        {
                            VarietyId = new Guid("e99c49c6-095b-4adc-b51c-c19f3ffff385"),
                            BuddingPeriod = 0,
                            ChestnutBlightResistance = 0,
                            Conservation = 0,
                            Crop = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FloweringPeriod = 0,
                            InkDiseaseResistance = 0,
                            IsActive = true,
                            IsPublished = true,
                            MaturityPeriod = 0,
                            Name = "Yixian Large",
                            Peeling = 0,
                            PollenType = 0,
                            Vigor = 0
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyFruitSize", b =>
                {
                    b.Property<Guid>("VarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FruitSizeId")
                        .HasColumnType("int");

                    b.HasKey("VarietyId", "FruitSizeId");

                    b.HasIndex("FruitSizeId");

                    b.ToTable("VarietyFruitSizes", (string)null);

                    b.HasData(
                        new
                        {
                            VarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77"),
                            FruitSizeId = 5
                        },
                        new
                        {
                            VarietyId = new Guid("fba92871-4a3c-4978-fcd6-08db87b43c2d"),
                            FruitSizeId = 4
                        },
                        new
                        {
                            VarietyId = new Guid("fba92871-4a3c-4978-fcd6-08db87b43c2d"),
                            FruitSizeId = 5
                        },
                        new
                        {
                            VarietyId = new Guid("8fc8f311-3ce9-42e2-fcd7-08db87b43c2d"),
                            FruitSizeId = 5
                        },
                        new
                        {
                            VarietyId = new Guid("ce7bf581-cd82-497e-a813-319dd7fcd922"),
                            FruitSizeId = 3
                        },
                        new
                        {
                            VarietyId = new Guid("ce7bf581-cd82-497e-a813-319dd7fcd922"),
                            FruitSizeId = 4
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyGraftingCompatibility", b =>
                {
                    b.Property<Guid>("RootstockVarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GraftedVarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RootstockVarietyId", "GraftedVarietyId");

                    b.HasIndex("GraftedVarietyId");

                    b.ToTable("VarietyGrafting", (string)null);

                    b.HasData(
                        new
                        {
                            RootstockVarietyId = new Guid("8fc8f311-3ce9-42e2-fcd7-08db87b43c2d"),
                            GraftedVarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77")
                        },
                        new
                        {
                            RootstockVarietyId = new Guid("8fc8f311-3ce9-42e2-fcd7-08db87b43c2d"),
                            GraftedVarietyId = new Guid("ce7bf581-cd82-497e-a813-319dd7fcd922")
                        },
                        new
                        {
                            RootstockVarietyId = new Guid("fba92871-4a3c-4978-fcd6-08db87b43c2d"),
                            GraftedVarietyId = new Guid("ce7bf581-cd82-497e-a813-319dd7fcd922")
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyImage", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImageId");

                    b.HasIndex("VarietyId");

                    b.ToTable("VarietyImages", (string)null);

                    b.HasData(
                        new
                        {
                            ImageId = new Guid("be9cca3d-4e9a-4e75-b813-9279f79f7f75"),
                            VarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77")
                        },
                        new
                        {
                            ImageId = new Guid("bf77ff2d-a488-4f6d-847b-3c880239a53f"),
                            VarietyId = new Guid("fba92871-4a3c-4978-fcd6-08db87b43c2d")
                        },
                        new
                        {
                            ImageId = new Guid("ee93870c-a4ad-46f7-b5dc-f36ae12ed3a3"),
                            VarietyId = new Guid("8fc8f311-3ce9-42e2-fcd7-08db87b43c2d")
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyPollenCompatibility", b =>
                {
                    b.Property<Guid>("PollenizerVarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetVarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PollenizerVarietyId", "TargetVarietyId");

                    b.HasIndex("TargetVarietyId");

                    b.ToTable("VarietyPollenizers", (string)null);

                    b.HasData(
                        new
                        {
                            PollenizerVarietyId = new Guid("fba92871-4a3c-4978-fcd6-08db87b43c2d"),
                            TargetVarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77")
                        },
                        new
                        {
                            PollenizerVarietyId = new Guid("8fc8f311-3ce9-42e2-fcd7-08db87b43c2d"),
                            TargetVarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77")
                        },
                        new
                        {
                            PollenizerVarietyId = new Guid("ce7bf581-cd82-497e-a813-319dd7fcd922"),
                            TargetVarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77")
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietySpecies", b =>
                {
                    b.Property<Guid>("VarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("VarietyId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("VarietySpecies");

                    b.HasData(
                        new
                        {
                            VarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77"),
                            SpeciesId = 1
                        },
                        new
                        {
                            VarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77"),
                            SpeciesId = 2
                        },
                        new
                        {
                            VarietyId = new Guid("fba92871-4a3c-4978-fcd6-08db87b43c2d"),
                            SpeciesId = 1
                        },
                        new
                        {
                            VarietyId = new Guid("fba92871-4a3c-4978-fcd6-08db87b43c2d"),
                            SpeciesId = 2
                        },
                        new
                        {
                            VarietyId = new Guid("8fc8f311-3ce9-42e2-fcd7-08db87b43c2d"),
                            SpeciesId = 1
                        },
                        new
                        {
                            VarietyId = new Guid("8fc8f311-3ce9-42e2-fcd7-08db87b43c2d"),
                            SpeciesId = 2
                        },
                        new
                        {
                            VarietyId = new Guid("ce7bf581-cd82-497e-a813-319dd7fcd922"),
                            SpeciesId = 1
                        },
                        new
                        {
                            VarietyId = new Guid("ce7bf581-cd82-497e-a813-319dd7fcd922"),
                            SpeciesId = 2
                        },
                        new
                        {
                            VarietyId = new Guid("dd423ce9-41e7-4c86-804a-9f4ade0b08f1"),
                            SpeciesId = 3
                        },
                        new
                        {
                            VarietyId = new Guid("dd423ce9-41e7-4c86-804a-9f4ade0b08f1"),
                            SpeciesId = 8
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "8bb25040-0173-4bb2-bfdf-b174f6361345",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "cfc4d095-9347-4604-a8e5-4620d990b197",
                            Name = "Expert",
                            NormalizedName = "EXPERT"
                        },
                        new
                        {
                            Id = "f5ca387b-0f47-4770-8379-f1ab769a1c95",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KestenApp.Data.Models.Garden", b =>
                {
                    b.HasOne("KestenApp.Data.Models.ApplicationUser", "User")
                        .WithMany("Gardens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KestenApp.Data.Models.Specimen", b =>
                {
                    b.HasOne("KestenApp.Data.Models.Garden", "Garden")
                        .WithMany("Specimens")
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KestenApp.Data.Models.ApplicationUser", "User")
                        .WithMany("Specimens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.Variety", "Variety")
                        .WithMany("Specimens")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Garden");

                    b.Navigation("User");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyFruitSize", b =>
                {
                    b.HasOne("KestenApp.Data.Models.FruitSize", "FruitSize")
                        .WithMany("Varieties")
                        .HasForeignKey("FruitSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.Variety", "Variety")
                        .WithMany("FruitSizes")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FruitSize");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyGraftingCompatibility", b =>
                {
                    b.HasOne("KestenApp.Data.Models.Variety", "GraftedVariety")
                        .WithMany("IsGraftedOn")
                        .HasForeignKey("GraftedVarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.Variety", "RootstockVariety")
                        .WithMany("IsRootstockFor")
                        .HasForeignKey("RootstockVarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GraftedVariety");

                    b.Navigation("RootstockVariety");
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyImage", b =>
                {
                    b.HasOne("KestenApp.Data.Models.Variety", "Variety")
                        .WithMany("VarietyImages")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyPollenCompatibility", b =>
                {
                    b.HasOne("KestenApp.Data.Models.Variety", "PollenizerVariety")
                        .WithMany("IsPollenizerFor")
                        .HasForeignKey("PollenizerVarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.Variety", "TargetVariety")
                        .WithMany("IsPollenizedBy")
                        .HasForeignKey("TargetVarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PollenizerVariety");

                    b.Navigation("TargetVariety");
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietySpecies", b =>
                {
                    b.HasOne("KestenApp.Data.Models.Species", "Species")
                        .WithMany("Varieties")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.Variety", "Variety")
                        .WithMany("Species")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("KestenApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("KestenApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("KestenApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KestenApp.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Gardens");

                    b.Navigation("Specimens");
                });

            modelBuilder.Entity("KestenApp.Data.Models.FruitSize", b =>
                {
                    b.Navigation("Varieties");
                });

            modelBuilder.Entity("KestenApp.Data.Models.Garden", b =>
                {
                    b.Navigation("Specimens");
                });

            modelBuilder.Entity("KestenApp.Data.Models.Species", b =>
                {
                    b.Navigation("Varieties");
                });

            modelBuilder.Entity("KestenApp.Data.Models.Variety", b =>
                {
                    b.Navigation("FruitSizes");

                    b.Navigation("IsGraftedOn");

                    b.Navigation("IsPollenizedBy");

                    b.Navigation("IsPollenizerFor");

                    b.Navigation("IsRootstockFor");

                    b.Navigation("Species");

                    b.Navigation("Specimens");

                    b.Navigation("VarietyImages");
                });
#pragma warning restore 612, 618
        }
    }
}
