// <auto-generated />
using System;
using KestenApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KestenApp.Data.Migrations
{
    [DbContext(typeof(KestenDbContext))]
    partial class KestenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KestenApp.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KestenApp.Data.Models.FruitSize", b =>
                {
                    b.Property<int>("FruitSizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FruitSizeId"), 1L, 1);

                    b.Property<int?>("FruitsPerKgMax")
                        .HasColumnType("int");

                    b.Property<int?>("FruitsPerKgMin")
                        .HasColumnType("int");

                    b.Property<int?>("FruitsWeightMax")
                        .HasColumnType("int");

                    b.Property<int?>("FruitsWeightMin")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FruitSizeId");

                    b.ToTable("FruitSizes");

                    b.HasData(
                        new
                        {
                            FruitSizeId = 1,
                            Name = "Varying"
                        },
                        new
                        {
                            FruitSizeId = 2,
                            FruitsPerKgMax = 1000,
                            FruitsPerKgMin = 84,
                            FruitsWeightMax = 12,
                            FruitsWeightMin = 1,
                            Name = "Small"
                        },
                        new
                        {
                            FruitSizeId = 3,
                            FruitsPerKgMax = 83,
                            FruitsPerKgMin = 67,
                            FruitsWeightMax = 15,
                            FruitsWeightMin = 13,
                            Name = "Medium"
                        },
                        new
                        {
                            FruitSizeId = 4,
                            FruitsPerKgMax = 66,
                            FruitsPerKgMin = 56,
                            FruitsWeightMax = 18,
                            FruitsWeightMin = 16,
                            Name = "Large"
                        },
                        new
                        {
                            FruitSizeId = 5,
                            FruitsPerKgMax = 55,
                            FruitsPerKgMin = 15,
                            FruitsWeightMax = 100,
                            FruitsWeightMin = 18,
                            Name = "XL"
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.Garden", b =>
                {
                    b.Property<Guid>("GardenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GardenId");

                    b.HasIndex("UserId");

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("KestenApp.Data.Models.Image", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("KestenApp.Data.Models.Species", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpeciesId"), 1L, 1);

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortLatinName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpeciesId");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            SpeciesId = 1,
                            CommonName = "European chestnut",
                            LatinName = "Castanea sativa",
                            ShortLatinName = "Sativa"
                        },
                        new
                        {
                            SpeciesId = 2,
                            CommonName = "Japanese chestnut",
                            LatinName = "Castanea crenata",
                            ShortLatinName = "Crenata"
                        },
                        new
                        {
                            SpeciesId = 3,
                            CommonName = "Chinese chestnut",
                            LatinName = "Castanea mollissima",
                            ShortLatinName = "Mollissima"
                        },
                        new
                        {
                            SpeciesId = 4,
                            CommonName = "American chestnut",
                            LatinName = "Castanea dentata",
                            ShortLatinName = "Dentata"
                        },
                        new
                        {
                            SpeciesId = 5,
                            CommonName = "Allegheny chinkapin",
                            LatinName = "Castanea pumila",
                            ShortLatinName = "Pumila"
                        },
                        new
                        {
                            SpeciesId = 6,
                            CommonName = "Ozark chinkapin",
                            LatinName = "Castanea ozarkensis",
                            ShortLatinName = "Ozarkensis"
                        },
                        new
                        {
                            SpeciesId = 7,
                            CommonName = "Chinese chinkapin",
                            LatinName = "Castanea henryi",
                            ShortLatinName = "Henryi"
                        },
                        new
                        {
                            SpeciesId = 8,
                            CommonName = "Seguin's chestnut",
                            LatinName = "Castanea seguinii",
                            ShortLatinName = "Seguinii"
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.Specimen", b =>
                {
                    b.Property<Guid>("SpecimenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Altitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<Guid?>("GardenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SpecimenId");

                    b.HasIndex("GardenId");

                    b.HasIndex("UserId");

                    b.HasIndex("VarietyId");

                    b.ToTable("Specimens");
                });

            modelBuilder.Entity("KestenApp.Data.Models.Variety", b =>
                {
                    b.Property<Guid>("VarietyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChestnutBlightResistance")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("InkDiseaseResistance")
                        .HasColumnType("int");

                    b.Property<bool?>("IsMarron")
                        .HasColumnType("bit");

                    b.Property<int>("MaturityPeriod")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Peeling")
                        .HasColumnType("int");

                    b.Property<int>("PollenType")
                        .HasColumnType("int");

                    b.HasKey("VarietyId");

                    b.ToTable("Varieties", (string)null);

                    b.HasData(
                        new
                        {
                            VarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77"),
                            ChestnutBlightResistance = 3,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bouche de Bétizac is a French chestnut cultivar developed in 1962 by INRA at the station of Malemort-sur-Corrèze near Brive. It is a controlled hybrid between Castanea sativa and Castanea crenata (female Bouche rouge × male Castanea crenata CA04). This variety produces large to very large chestnuts. It has very good flavor for a hybrid. With Marigoule, it is the variety currently most cultivated in the French chestnut groves because it is very productive (3 tons per hectare on average). Its fruit is bright, light chestnut-brown quickly turning brown and dark brown.",
                            InkDiseaseResistance = 1,
                            IsMarron = true,
                            MaturityPeriod = 2,
                            Name = "Bouche de Bétizac",
                            Peeling = 3,
                            PollenType = 1
                        },
                        new
                        {
                            VarietyId = new Guid("5f633911-c1da-4b97-b931-731540767fdb"),
                            ChestnutBlightResistance = 2,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Marigoule is the name of a french hybrid of chestnut (synonym M.15 or CA 15), cross between a European chestnut (Castanea sativa) and Japanese (Castanea crenata). In 1986, it originated from a Migoule orchard in Ussac in Corrèze. Marigoule (a contraction of Marron of Migoule) is a very tasty chestnut. It should be planted in rather low altitude in very sunny areas and protected from the wind (up to 300 m elevation for South-West orchard orientation or up to 400 m elevation in South-East orchard orientation). Otherwise its productivity remains small. In France, it is grown mainly South of the Dordogne and Lot-et-Garonne for the fresh market production because of the nuts beautiful appearance.",
                            InkDiseaseResistance = 3,
                            IsMarron = true,
                            MaturityPeriod = 3,
                            Name = "Marigoule",
                            Peeling = 3,
                            PollenType = 2
                        },
                        new
                        {
                            VarietyId = new Guid("32802866-9e8a-42af-8f0f-b7de649284a4"),
                            ChestnutBlightResistance = 3,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Marsol (aka Marisol) is a natural chestnut hybrid, a cross between a European chestnut (Castanea sativa) and Japanese (Castanea crenata) (CA 07). INRA produced this variety from Lalevade-d'Ardèche. It is mainly used as a rootstock because of its good graft compatibility with many varieties. As a rootstock, it is more vigorous than Maraval (equal to Bouche de Betizac or Comballe).",
                            InkDiseaseResistance = 3,
                            IsMarron = true,
                            MaturityPeriod = 3,
                            Name = "Marsol",
                            Peeling = 3,
                            PollenType = 3
                        },
                        new
                        {
                            VarietyId = new Guid("eef4edd6-1516-4015-8ea6-c9da32a20739"),
                            ChestnutBlightResistance = 1,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Precoce Migoule is a chestnut hybrid (CA 48), a natural cross between a European chestnut (Castanea sativa) and a Japanese chestnut (Castanea crenata). It was discovered by J. Dufrenoy at the orchard of Migoule in Brive-la-Gaillarde. The tree is vigorous and erect growing with growth of a metre (3 ft) or more in a season if the conditions are right. It is a large sized chestnut tree with height reaching 20 m (60 ft) or more and 7.5-10 m (25-35 ft) wide. Trees start to bear after 3 to 5 years. Full nut production in 12 - 20 years depending on the location.",
                            InkDiseaseResistance = 2,
                            IsMarron = true,
                            MaturityPeriod = 2,
                            Name = "Précoce Migoule",
                            Peeling = 3,
                            PollenType = 2
                        },
                        new
                        {
                            VarietyId = new Guid("bf33a54f-0a3c-4758-8a1a-85c62da4c88d"),
                            ChestnutBlightResistance = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            InkDiseaseResistance = 0,
                            MaturityPeriod = 0,
                            Name = "Pandora",
                            Peeling = 0,
                            PollenType = 0
                        },
                        new
                        {
                            VarietyId = new Guid("16f81d57-8d2a-4f1e-bc46-793e17138491"),
                            ChestnutBlightResistance = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            InkDiseaseResistance = 0,
                            MaturityPeriod = 0,
                            Name = "Nevada",
                            Peeling = 0,
                            PollenType = 0
                        },
                        new
                        {
                            VarietyId = new Guid("46c3d3af-31de-4e8d-956b-b342aee292c1"),
                            ChestnutBlightResistance = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            InkDiseaseResistance = 0,
                            MaturityPeriod = 0,
                            Name = "Long Street",
                            Peeling = 0,
                            PollenType = 0
                        },
                        new
                        {
                            VarietyId = new Guid("2efbfe74-061f-4682-812b-e39885504c39"),
                            ChestnutBlightResistance = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            InkDiseaseResistance = 0,
                            MaturityPeriod = 0,
                            Name = "AU 2-18",
                            Peeling = 0,
                            PollenType = 0
                        },
                        new
                        {
                            VarietyId = new Guid("75965271-3f74-4b8b-8709-95069dc847ed"),
                            ChestnutBlightResistance = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            InkDiseaseResistance = 0,
                            MaturityPeriod = 0,
                            Name = "AU Super",
                            Peeling = 0,
                            PollenType = 0
                        },
                        new
                        {
                            VarietyId = new Guid("3e07d035-e38c-4950-a3bc-a158ba8786d9"),
                            ChestnutBlightResistance = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            InkDiseaseResistance = 0,
                            MaturityPeriod = 0,
                            Name = "Black Satin",
                            Peeling = 0,
                            PollenType = 0
                        },
                        new
                        {
                            VarietyId = new Guid("aae30cf2-b627-47eb-9ebe-267337385f2b"),
                            ChestnutBlightResistance = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            InkDiseaseResistance = 0,
                            MaturityPeriod = 0,
                            Name = "Chushuhong",
                            Peeling = 0,
                            PollenType = 0
                        },
                        new
                        {
                            VarietyId = new Guid("81f4e185-6c94-4996-9370-e11155227285"),
                            ChestnutBlightResistance = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            InkDiseaseResistance = 0,
                            MaturityPeriod = 0,
                            Name = "Emalyn's Purple",
                            Peeling = 0,
                            PollenType = 0
                        },
                        new
                        {
                            VarietyId = new Guid("ae3af6b7-de9e-445d-8b3d-7a3adefd77f5"),
                            ChestnutBlightResistance = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            InkDiseaseResistance = 0,
                            MaturityPeriod = 0,
                            Name = "Gideon",
                            Peeling = 0,
                            PollenType = 0
                        },
                        new
                        {
                            VarietyId = new Guid("dabc242c-cd4b-45e5-acd2-e976a6e19c7c"),
                            ChestnutBlightResistance = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            InkDiseaseResistance = 0,
                            MaturityPeriod = 0,
                            Name = "Jenny",
                            Peeling = 0,
                            PollenType = 0
                        },
                        new
                        {
                            VarietyId = new Guid("3b770733-91c1-49c9-95e3-e5ab66a4896e"),
                            ChestnutBlightResistance = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            InkDiseaseResistance = 0,
                            MaturityPeriod = 0,
                            Name = "Jiaoza",
                            Peeling = 0,
                            PollenType = 0
                        },
                        new
                        {
                            VarietyId = new Guid("2570968e-3fdc-4d19-8d13-b10f660b2509"),
                            ChestnutBlightResistance = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            InkDiseaseResistance = 0,
                            MaturityPeriod = 0,
                            Name = "Payne",
                            Peeling = 0,
                            PollenType = 0
                        },
                        new
                        {
                            VarietyId = new Guid("58a7f45d-84c8-4ed1-a46c-9f920a4205b2"),
                            ChestnutBlightResistance = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            InkDiseaseResistance = 0,
                            MaturityPeriod = 0,
                            Name = "Peach",
                            Peeling = 0,
                            PollenType = 0
                        },
                        new
                        {
                            VarietyId = new Guid("061dc865-d58d-4f68-8ebb-e409819c7c1a"),
                            ChestnutBlightResistance = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            InkDiseaseResistance = 0,
                            MaturityPeriod = 0,
                            Name = "Qing",
                            Peeling = 0,
                            PollenType = 0
                        },
                        new
                        {
                            VarietyId = new Guid("be128efb-74cd-4a7d-ac88-b6a0ddc0a48d"),
                            ChestnutBlightResistance = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            InkDiseaseResistance = 0,
                            MaturityPeriod = 0,
                            Name = "Qingza",
                            Peeling = 0,
                            PollenType = 0
                        },
                        new
                        {
                            VarietyId = new Guid("e2281a46-4523-4cff-99da-a4b815327589"),
                            ChestnutBlightResistance = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            InkDiseaseResistance = 0,
                            MaturityPeriod = 0,
                            Name = "Royalmark",
                            Peeling = 0,
                            PollenType = 0
                        },
                        new
                        {
                            VarietyId = new Guid("cc2f2f4b-24d0-458b-8442-ac721f32e0c4"),
                            ChestnutBlightResistance = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            InkDiseaseResistance = 0,
                            MaturityPeriod = 0,
                            Name = "YGF",
                            Peeling = 0,
                            PollenType = 0
                        },
                        new
                        {
                            VarietyId = new Guid("07b2417c-b1b4-4a28-81e5-880915e0ba9e"),
                            ChestnutBlightResistance = 0,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            InkDiseaseResistance = 0,
                            MaturityPeriod = 0,
                            Name = "Yixian Large",
                            Peeling = 0,
                            PollenType = 0
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyFruitSize", b =>
                {
                    b.Property<Guid>("VarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FruitSizeId")
                        .HasColumnType("int");

                    b.HasKey("VarietyId", "FruitSizeId");

                    b.HasIndex("FruitSizeId");

                    b.ToTable("VarietyFruitSize");

                    b.HasData(
                        new
                        {
                            VarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77"),
                            FruitSizeId = 5
                        },
                        new
                        {
                            VarietyId = new Guid("5f633911-c1da-4b97-b931-731540767fdb"),
                            FruitSizeId = 4
                        },
                        new
                        {
                            VarietyId = new Guid("5f633911-c1da-4b97-b931-731540767fdb"),
                            FruitSizeId = 5
                        },
                        new
                        {
                            VarietyId = new Guid("32802866-9e8a-42af-8f0f-b7de649284a4"),
                            FruitSizeId = 5
                        },
                        new
                        {
                            VarietyId = new Guid("eef4edd6-1516-4015-8ea6-c9da32a20739"),
                            FruitSizeId = 3
                        },
                        new
                        {
                            VarietyId = new Guid("eef4edd6-1516-4015-8ea6-c9da32a20739"),
                            FruitSizeId = 4
                        });
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyGraftingCompatibility", b =>
                {
                    b.Property<Guid>("RootstockVarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GraftedVarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RootstockVarietyId", "GraftedVarietyId");

                    b.HasIndex("GraftedVarietyId");

                    b.ToTable("VarietyGrafting", (string)null);
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyPollenCompatibility", b =>
                {
                    b.Property<Guid>("PollenizerVarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetVarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PollenizerVarietyId", "TargetVarietyId");

                    b.HasIndex("TargetVarietyId");

                    b.ToTable("VarietyPollenizers", (string)null);
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietySpecies", b =>
                {
                    b.Property<int>("VarietySpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VarietySpeciesId"), 1L, 1);

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<Guid>("VarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VarietySpeciesId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("VarietyId");

                    b.ToTable("VarietySpecies");

                    b.HasData(
                        new
                        {
                            VarietySpeciesId = 1,
                            SpeciesId = 1,
                            VarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77")
                        },
                        new
                        {
                            VarietySpeciesId = 2,
                            SpeciesId = 2,
                            VarietyId = new Guid("46bd8dc8-ca0a-4648-a9a9-ea4ad91e1b77")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VarietyImages", b =>
                {
                    b.Property<Guid>("ImagesImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VarietiesVarietyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImagesImageId", "VarietiesVarietyId");

                    b.HasIndex("VarietiesVarietyId");

                    b.ToTable("VarietyImages");
                });

            modelBuilder.Entity("KestenApp.Data.Models.Garden", b =>
                {
                    b.HasOne("KestenApp.Data.Models.ApplicationUser", "User")
                        .WithMany("Gardens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KestenApp.Data.Models.Specimen", b =>
                {
                    b.HasOne("KestenApp.Data.Models.Garden", "Garden")
                        .WithMany("Specimens")
                        .HasForeignKey("GardenId");

                    b.HasOne("KestenApp.Data.Models.ApplicationUser", "User")
                        .WithMany("Specimens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.Variety", "Variety")
                        .WithMany()
                        .HasForeignKey("VarietyId");

                    b.Navigation("Garden");

                    b.Navigation("User");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyFruitSize", b =>
                {
                    b.HasOne("KestenApp.Data.Models.FruitSize", "FruitSize")
                        .WithMany("Varieties")
                        .HasForeignKey("FruitSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.Variety", "Variety")
                        .WithMany("FruitSizes")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FruitSize");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyGraftingCompatibility", b =>
                {
                    b.HasOne("KestenApp.Data.Models.Variety", "GraftedVariety")
                        .WithMany("IsGraftedOn")
                        .HasForeignKey("GraftedVarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.Variety", "RootstockVariety")
                        .WithMany("IsRootstockFor")
                        .HasForeignKey("RootstockVarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GraftedVariety");

                    b.Navigation("RootstockVariety");
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietyPollenCompatibility", b =>
                {
                    b.HasOne("KestenApp.Data.Models.Variety", "PollenizerVariety")
                        .WithMany("IsPollenizerFor")
                        .HasForeignKey("PollenizerVarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.Variety", "TargetVariety")
                        .WithMany("IsPollenizedBy")
                        .HasForeignKey("TargetVarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PollenizerVariety");

                    b.Navigation("TargetVariety");
                });

            modelBuilder.Entity("KestenApp.Data.Models.VarietySpecies", b =>
                {
                    b.HasOne("KestenApp.Data.Models.Species", "Species")
                        .WithMany("Varieties")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.Variety", "Variety")
                        .WithMany("Species")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("KestenApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("KestenApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("KestenApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VarietyImages", b =>
                {
                    b.HasOne("KestenApp.Data.Models.Image", null)
                        .WithMany()
                        .HasForeignKey("ImagesImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KestenApp.Data.Models.Variety", null)
                        .WithMany()
                        .HasForeignKey("VarietiesVarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KestenApp.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Gardens");

                    b.Navigation("Specimens");
                });

            modelBuilder.Entity("KestenApp.Data.Models.FruitSize", b =>
                {
                    b.Navigation("Varieties");
                });

            modelBuilder.Entity("KestenApp.Data.Models.Garden", b =>
                {
                    b.Navigation("Specimens");
                });

            modelBuilder.Entity("KestenApp.Data.Models.Species", b =>
                {
                    b.Navigation("Varieties");
                });

            modelBuilder.Entity("KestenApp.Data.Models.Variety", b =>
                {
                    b.Navigation("FruitSizes");

                    b.Navigation("IsGraftedOn");

                    b.Navigation("IsPollenizedBy");

                    b.Navigation("IsPollenizerFor");

                    b.Navigation("IsRootstockFor");

                    b.Navigation("Species");
                });
#pragma warning restore 612, 618
        }
    }
}
